import { Report } from '../../../../core/models/report.model';

export const REPORT_MOCK_DATA: Report[] = [
  {
    id: 1,
    name: 'Test Report',
    created: 'Dec 24, 2020',
    modified: 'Dec 24, 2020',
    owner: 'zendudemo-trax@zenduit.com',
    form: 'Billing Chilling Regular Form',
  },
  {
    id: 2,
    name: 'Test Report 2',
    created: 'Dec 26, 2020',
    modified: 'Dec 26, 2020',
    owner: 'johndodson@zenduit.com',
    form: 'Geotab odometer-test',
  },
  {
    id: 3,
    name: 'SAWG Install Report',
    created: 'Dec 27, 2020',
    modified: 'Dec 29, 2020',
    owner: 'joshuatreffue@zenduit.com',
    form: 'Bill of Landing Template',
  },
  {
    id: 4,
    name: 'Five and Ambulance for Wood Buffalo',
    created: 'Dec 28, 2020',
    modified: 'Dec 29, 2020',
    owner: 'christianbale@zenduit.com',
    form: 'Product Delivery Form Test',
  },
  {
    id: 5,
    name: 'Test Report 3',
    created: 'Dec 30, 2020',
    modified: 'Dec 30, 2020',
    owner: 'margaretleblane@zenduit.com',
    form: 'Product test Form',
  },
  {
    id: 6,
    name: 'Driver Activity Report',
    created: 'Jan 01, 2021',
    modified: 'Jan 01, 2021',
    owner: 'driver@zenduit.com',
    form: 'Driver Form',
  },
  {
    id: 7,
    name: 'Fuel Summary',
    created: 'Jan 03, 2021',
    modified: 'Jan 03, 2021',
    owner: 'fuel@zenduit.com',
    form: 'Fuel Tracker',
  },
  {
    id: 8,
    name: 'Vehicle Inspection',
    created: 'Jan 05, 2021',
    modified: 'Jan 05, 2021',
    owner: 'inspection@zenduit.com',
    form: 'Inspection Form',
  },
  {
    id: 9,
    name: 'Mileage Report',
    created: 'Jan 08, 2021',
    modified: 'Jan 08, 2021',
    owner: 'mileage@zenduit.com',
    form: 'Mileage Form',
  },

  {
    id: 10,
    name: 'Daily Safety Checklist',
    created: 'Jan 10, 2021',
    modified: 'Jan 10, 2021',
    owner: 'safety@zenduit.com',
    form: 'Safety Inspection Form',
  },
  {
    id: 11,
    name: 'Fleet Maintenance Log',
    created: 'Jan 11, 2021',
    modified: 'Jan 12, 2021',
    owner: 'fleet@zenduit.com',
    form: 'Maintenance Tracker',
  },
  {
    id: 12,
    name: 'Expense Approval Report',
    created: 'Jan 12, 2021',
    modified: 'Jan 12, 2021',
    owner: 'finance@zenduit.com',
    form: 'Expense Approval Workflow',
  },
  {
    id: 13,
    name: 'Incident Investigation Report',
    created: 'Jan 13, 2021',
    modified: 'Jan 14, 2021',
    owner: 'incident@zenduit.com',
    form: 'Incident Tracking Form',
  },
  {
    id: 14,
    name: 'Customer Visit Summary',
    created: 'Jan 14, 2021',
    modified: 'Jan 14, 2021',
    owner: 'sales@zenduit.com',
    form: 'Customer Visit Log',
  },
  {
    id: 15,
    name: 'Warehouse Inventory Audit',
    created: 'Jan 15, 2021',
    modified: 'Jan 15, 2021',
    owner: 'warehouse@zenduit.com',
    form: 'Inventory Audit Form',
  }
];
